from __future__ import annotations

import asyncio
import json
import subprocess
from pathlib import Path
from typing import Any, Awaitable, Callable

import httpx

from app.models.domain import Capability, CapabilityState, PublishPreset, PublishRequest
from app.settings.config import Settings

ProgressReporter = Callable[[int, str], Awaitable[None]]
CancelChecker = Callable[[], bool]


class PublisherAdapter:
    def capability(self) -> Capability:
        raise NotImplementedError

    def presets(self) -> list[PublishPreset]:
        return [
            PublishPreset(
                id="review-board",
                name="Review Board Pack",
                template="board-deck",
                category="governance",
                description="Structured HTML package for architecture and safety review boards.",
            ),
            PublishPreset(
                id="collaborator-handout",
                name="Collaborator Handout",
                template="collaborator-handout",
                category="presentation",
                description="Reading-mode package for presentation and collaborator sharing.",
            ),
        ]

    async def publish(
        self,
        request: PublishRequest,
        output_dir: Path,
        report: ProgressReporter,
        cancel_requested: CancelChecker,
    ) -> dict[str, Any]:
        raise NotImplementedError


class StubPublisherAdapter(PublisherAdapter):
    def capability(self) -> Capability:
        return Capability(
            name="publish",
            state=CapabilityState.READY,
            reason="Stub publisher is enabled. It produces concrete HTML artifacts while keeping the integration boundary pluggable.",
            source="integration",
        )

    async def publish(
        self,
        request: PublishRequest,
        output_dir: Path,
        report: ProgressReporter,
        cancel_requested: CancelChecker,
    ) -> dict[str, Any]:
        steps = [
            (20, "Validating publish request"),
            (45, "Rendering collaborator-facing content"),
            (75, "Writing artifact package"),
            (100, "Publish completed"),
        ]
        for progress, message in steps:
            if cancel_requested():
                return {"cancelled": True}
            await report(progress, message)
            await asyncio.sleep(0.6)

        output_dir.mkdir(parents=True, exist_ok=True)
        artifact_path = output_dir / f"publish-{request.project_id}-{request.branch_id}.html"
        artifact_path.write_text(
            """
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>TWC Publish Artifact</title>
    <style>
      body { font-family: 'IBM Plex Sans', Arial, sans-serif; margin: 2rem; background: #f5f7fb; color: #14213d; }
      .card { background: white; border-radius: 18px; padding: 1.5rem; box-shadow: 0 18px 50px rgba(20,33,61,0.08); }
      h1 { font-family: 'Space Grotesk', sans-serif; }
      code { background: #eef3fb; padding: 0.2rem 0.4rem; border-radius: 6px; }
    </style>
  </head>
  <body>
    <div class="card">
      <h1>Publish Artifact</h1>
      <p>This artifact was generated by the stub publisher adapter. Swap the adapter for a CLI or webhook integration to target a live Collaborator publishing pipeline.</p>
      <ul>
        <li>Project: <code>%s</code></li>
        <li>Branch: <code>%s</code></li>
        <li>Scope: <code>%s</code></li>
        <li>Template: <code>%s</code></li>
        <li>Category: <code>%s</code></li>
      </ul>
    </div>
  </body>
</html>
            """.strip()
            % (request.project_id, request.branch_id, request.scope, request.template, request.category),
            encoding="utf-8",
        )
        return {"artifact_path": str(artifact_path), "mode": "stub"}


class CliPublisherAdapter(PublisherAdapter):
    def __init__(self, command: str) -> None:
        self.command = command

    def capability(self) -> Capability:
        return Capability(
            name="publish",
            state=CapabilityState.READY,
            reason="External CLI publisher is configured.",
            source="integration",
        )

    async def publish(
        self,
        request: PublishRequest,
        output_dir: Path,
        report: ProgressReporter,
        cancel_requested: CancelChecker,
    ) -> dict[str, Any]:
        if cancel_requested():
            return {"cancelled": True}
        await report(20, "Executing external publisher CLI")
        payload_path = output_dir / "publish-request.json"
        payload_path.parent.mkdir(parents=True, exist_ok=True)
        payload_path.write_text(request.model_dump_json(indent=2), encoding="utf-8")
        completed = await asyncio.to_thread(
            subprocess.run,
            self.command,
            shell=True,
            check=False,
            capture_output=True,
            text=True,
        )
        await report(100, "External publisher finished")
        return {
            "mode": "cli",
            "return_code": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "payload_path": str(payload_path),
        }


class WebhookPublisherAdapter(PublisherAdapter):
    def __init__(self, webhook_url: str) -> None:
        self.webhook_url = webhook_url

    def capability(self) -> Capability:
        return Capability(
            name="publish",
            state=CapabilityState.READY,
            reason="External webhook publisher is configured.",
            source="integration",
        )

    async def publish(
        self,
        request: PublishRequest,
        output_dir: Path,
        report: ProgressReporter,
        cancel_requested: CancelChecker,
    ) -> dict[str, Any]:
        if cancel_requested():
            return {"cancelled": True}
        await report(35, "Submitting publish request to external job endpoint")
        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(self.webhook_url, json=request.model_dump(mode="json"))
            response.raise_for_status()
        await report(100, "Webhook publisher acknowledged the request")
        return {"mode": "webhook", "response": response.json() if response.content else {}}


def build_publisher(settings: Settings) -> PublisherAdapter:
    if settings.publisher_mode == "cli" and settings.publisher_command:
        return CliPublisherAdapter(settings.publisher_command)
    if settings.publisher_mode == "webhook" and settings.publisher_webhook_url:
        return WebhookPublisherAdapter(settings.publisher_webhook_url)
    return StubPublisherAdapter()
